---
- name: Bootstrap Ubuntu
  hosts: micro_pcs
  become: true

  tasks:
    - name: Update and upgrade apt packages
      apt:
        upgrade: yes
        update_cache: yes

    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install required packages
      apt:
        name:
          - curl
          - zsh
          - zsh-antigen
        state: present

    - name: Check if Oh My Zsh is installed
      stat:
        path: /home/{{ ansible_user }}/.oh-my-zsh
      register: ohmyzsh_check

    - name: Install Oh My Zsh
      shell: sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
      args:
        executable: /bin/bash
      become_user: james
      when: ohmyzsh_check.stat.isdir is not defined or not ohmyzsh_check.stat.isdir

    - name: Copy custom ZSH config file
      copy:
        src: .zshrc  
        dest: /home/james/.zshrc
        owner: james
        group: james
        
    - name: Remove carriage returns from .zshrc
      replace:
        path: /home/james/.zshrc
        regexp: '\r'
        replace: ''

    - name: Install GnuPG
      apt:
        name: gnupg
        state: present

    - name: Stat Check if 1Password is installed
      stat:
        path: /usr/bin/1password
      register: onepassword_stat_check

    - name: Download 1Password .deb package
      get_url:
        url: https://downloads.1password.com/linux/debian/amd64/stable/1password-latest.deb
        dest: /tmp/1password-latest.deb
      when: onepassword_stat_check.stat.exists is not defined or not onepassword_stat_check.stat.exists


    - name: Install 1Password
      apt:
        deb: /tmp/1password-latest.deb
      become: true
      when: onepassword_stat_check.stat.exists is not defined or not onepassword_stat_check.stat.exists

    - name: Check if firewalld is installed
      stat:
        path: /usr/sbin/firewalld
      register: firewalld_stat_check

    - name: Disable firewalld
      shell: "sudo systemctl stop firewalld & sudo systemctl disable firewalld"
      when: firewalld_stat_check.stat.exists

    - name: disable ipv4 forwarding
      shell: "echo 'net.ipv4.ip_forward=1' | sudo tee -a /etc/sysctl.conf"

    - name: Disable swap
      shell: sudo sed -i '/ swap / s/^\(.*\)$/#\1/g' /etc/fstab && sudo swapoff -a
