---
# Secrets mapping configuration
# Defines which 1Password items sync to Ansible Vault variables

# 1Password vault name
onepassword_vault: "homelab"

# Secrets to sync
secrets:
  # Technitium DNS API tokens
  - onepassword_item: "Technitium DNS1 API"
    onepassword_field: "credential"
    onepassword_field_type: "text"  # text field in 1Password
    vault_variable: "vault_technitium_dns1_token"
    description: "Technitium DNS1 API token"
    
  - onepassword_item: "Technitium DNS2 API"
    onepassword_field: "credential"
    onepassword_field_type: "text"
    vault_variable: "vault_technitium_dns2_token"
    description: "Technitium DNS2 API token"

  # DHCP failover shared secret
  - onepassword_item: "Technitium DHCP Failover"
    onepassword_field: "shared_secret"
    onepassword_field_type: "password"
    vault_variable: "vault_dhcp_failover_secret"
    description: "DHCP failover shared secret between DNS servers"

  # Proxmox credentials
  - onepassword_item: "Proxmox Terraform"
    onepassword_field: "credential"
    onepassword_field_type: "text"
    vault_variable: "vault_proxmox_token_secret"
    description: "Proxmox API token secret"
  
  # VM/LXC default password
  - onepassword_item: "Homelab VM Default"
    onepassword_field: "password"
    onepassword_field_type: "password"
    vault_variable: "vault_vm_default_password"
    description: "Default password for VMs and LXC containers"
  
  # Desktop SSH public key for infrastructure
  - onepassword_item: "Spraycheese Infrastructure SSH Key"
    onepassword_field: "public key"
    onepassword_field_type: "text"
    vault_variable: "vault_ssh_public_key"
    description: "SSH public key for infrastructure automation"
  

