apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: onepassword
  namespace: external-secrets-system
  labels:
    app.kubernetes.io/name: onepassword-secretstore
    app.kubernetes.io/part-of: external-secrets
spec:
  provider:
    onepassword:
      # Connect account using service account token
      # Create the token secret with:
      # kubectl create secret generic onepassword-token \
      #   -n external-secrets-system \
      #   --from-literal=token='<your-service-account-token>'
      auth:
        secretRef:
          connectTokenSecretRef:
            name: onepassword-token
            key: token
      
      # Your 1Password vault name
      # Must match vault in 1Password account
      vaults:
        homelab: 1

---
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: onepassword-cluster
  labels:
    app.kubernetes.io/name: onepassword-cluster-secretstore
    app.kubernetes.io/part-of: external-secrets
spec:
  provider:
    onepassword:
      auth:
        secretRef:
          connectTokenSecretRef:
            name: onepassword-token
            namespace: external-secrets-system
            key: token
      vaults:
        homelab: 1
