apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: proxmox-credentials
  namespace: tekton-pipelines
  labels:
    app.kubernetes.io/name: proxmox-credentials
    app.kubernetes.io/part-of: infrastructure
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  refreshInterval: 1h
  
  secretStoreRef:
    name: onepassword-cluster
    kind: ClusterSecretStore
  
  target:
    name: proxmox-creds
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      engineVersion: v2
      metadata:
        labels:
          app.kubernetes.io/name: proxmox-credentials
  
  data:
    # Proxmox API token secret
    - secretKey: api-token-secret
      remoteRef:
        key: Proxmox Terraform
        property: credential
    
    # VM default password
    - secretKey: vm-password
      remoteRef:
        key: Homelab VM Default
        property: password
